version: '3'

services:
  video_processor:
    build: ./video_processor
    ports:
      - "5000:5000"
    volumes:
      - shared_n8n_video_store:/data
      # Optional: Lokaler Code-Mount, um die Python-Skripte dynamisch anzupassen
      #- ./mein_python_code:/app

volumes:
  shared_data:
